# Generated by Django 5.0.7 on 2024-07-20 22:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('sobrenome', models.CharField(max_length=256)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=14)),
                ('data_de_nascimento', models.DateField()),
                ('prim_fone', models.CharField(max_length=64)),
                ('segu_fone', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('medico', models.BooleanField(default=False)),
                ('id_pessoa_cr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField()),
                ('prontuario', models.FileField(upload_to='')),
                ('data_de_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_pessoa_cr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_pessoa_pa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.pessoamodel')),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=64)),
                ('rqe', models.CharField(max_length=10, unique=True)),
                ('id_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.pessoamodel')),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=64)),
                ('numero', models.CharField(max_length=8)),
                ('bairro', models.CharField(max_length=64)),
                ('cidade', models.CharField(max_length=64)),
                ('uf', models.CharField(max_length=2)),
                ('complemento', models.CharField(max_length=128)),
                ('id_pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.pessoamodel')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('numero', models.CharField(max_length=12, unique=True)),
                ('inscricao', models.CharField(max_length=10)),
                ('situacao', models.CharField(max_length=10)),
                ('id_pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.pessoamodel')),
            ],
        ),
    ]
